# Generated by Django 4.0.6 on 2022-07-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_alter_category_id_propertyproductimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyProductBlog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=264)),
                ('sub_title', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='dashboard.product')),
            ],
        ),
    ]
