# Generated by Django 4.0.6 on 2022-07-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_propertyproductblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyproductblog',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
